version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src/apiserver"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/src/metaserver"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/src/objectserver"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/src/adminserver"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "yarn"
    directory: "/src/adminserver/ui"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(ui)"
      include: "scope"
