name: Release API Server

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.work
          cache: true
          cache-dependency-path: go.work.sum
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./src/apiserver
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GH_TK }}
