name: Release ADMIN Server

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./src/adminserver/go.mod
          cache: true
          cache-dependency-path: ./src/adminserver/go.sum

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: src/adminserver/ui

      - name: Build Frontend
        run: cd src/adminserver/ui && yarn && yarn run build
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./src/adminserver
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GH_TK }}
