# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Set up Yarn
      uses: mskelton/setup-yarn@v1
      with:
       flags: --immutable-cache
       
    - name: Build Vue
      run: cd src/adminserver/ui && yarn run build

    - name: Build AdminServer
      run: go build -v src/adminserver
    
    - name: Build ApiServer
      run: go build -v src/adminserver
      
    - name: Build MetaServer
      run: go build -v src/metaserver
      
    - name: Build ObjectServer
      run: go build -v src/objectserver
